id: ADEEFEF9F
base_file: f3B9F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:15:35.737773
  last_modified_at: 2022-06-15 20:15:35.737780
